version: '3'
services:
    nginx:
        build: ./containers/nginx
        container_name: nginx
        depends_on:
            - AERecommend
        ports:
            - "80:80"
        volumes:
            - ./containers/nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - /tmp/nginx_log:/var/log/nginx
    aerecommend:
        build: ./containers/AERecommend
        container_name: AERecommend
        ports:
            - "5000:5000"
        environment:
            ENV: PROD
        volumes:
            - ./containers/AERecommend/app:/app
            - /tmp/AERecommend:/tmp/AERecommend
