version: '3'
services:
    nginx:
        build: ./containers/nginx
        container_name: nginx
        depends_on:
            - core
        ports:
            - "80:80"
        volumes:
            - ./containers/nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - /tmp/nginx_log:/var/log/nginx
    core:
        build: ./containers/core
        container_name: core
        ports:
            - "5000:5000"
        environment:
            ENV: PROD
        volumes:
            - ./containers/core/app:/app
            - /tmp/core:/tmp/core
